upstream frontend {
    server ui:3000;
}

upstream backend {
    server api:8000;
}

upstream customer-service-api {
    server customer-service-api:8000;
}

upstream etl-automation-api {
    server etl-automation-api:8000;
}

upstream grafana {
    server grafana:3000;
}

server {
    listen 80;

    location /grafana {
        proxy_set_header Host $host;
        proxy_pass http://grafana;
    }

    location /grafana/api/live/ {
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
        proxy_set_header Host $host;
        proxy_pass http://grafana;
    }

    location /ui {
        proxy_redirect off;
        proxy_pass http://frontend/;
    }

    location /_next/static {
        proxy_redirect off;
        proxy_pass http://frontend/_next/static;
        alias /app/.next/static;
    }

    location /_next/webpack-hmr {
        proxy_pass http://frontend/_next/webpack-hmr;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
    }

    location /api/ {
        add_header Access-Control-Allow-Origin "*";
        add_header Access-Control-Allow-Methods "GET, POST, PUT, DELETE, OPTIONS, HEAD";
        # add_header Access-Control-Allow-Headers "content-type";
        add_header Access-Control-Allow-Headers "DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type";

        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header Host $host;

        proxy_buffering off;
        proxy_redirect off;
        proxy_pass http://backend/;
    }

    location /api/docs {
        proxy_redirect off;
        proxy_pass http://backend/docs;
    }

    location /use-cases/customer-service/ui {
        alias /usr/share/nginx/html/customer-service;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    location /use-cases/customer-service/api/ {
        add_header Access-Control-Allow-Origin "*";
        add_header Access-Control-Allow-Methods "GET, POST, PUT, DELETE, OPTIONS, HEAD";
        # add_header Access-Control-Allow-Headers "content-type";
        add_header Access-Control-Allow-Headers "DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type";

        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header Host $host;

        proxy_buffering off;
        proxy_redirect off;
        proxy_pass http://customer-service-api/;
    }

    location /use-cases/customer-service/api/docs {
        proxy_redirect off;
        proxy_pass http://customer-service-api/docs;
    }

    location /use-cases/etl-automation/ui {
        alias /usr/share/nginx/html/etl-automation;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    location /use-cases/etl-automation/api/ {
        add_header Access-Control-Allow-Origin "*";
        add_header Access-Control-Allow-Methods "GET, POST, PUT, DELETE, OPTIONS, HEAD";
        # add_header Access-Control-Allow-Headers "content-type";
        add_header Access-Control-Allow-Headers "DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type";

        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header Host $host;

        proxy_buffering off;
        proxy_redirect off;
        proxy_pass http://etl-automation-api/;
    }

    location /use-cases/etl-automation/api/docs {
        proxy_redirect off;
        proxy_pass http://etl-automation-api/docs;
    }
}
