server {
    listen 80;

    location / {
        proxy_pass https://nicholasgoh.github.io;
        proxy_set_header Host nicholasgoh.github.io;
    }

    location /langfuse {
        return 302 https://nicholasgoh.github.io/blog/reducing-cloud-bill;
    }

    location /grafana {
        return 302 https://nicholasgoh.github.io/blog/reducing-cloud-bill;
    }

    location /grafana/api/live/ {
        return 302 https://nicholasgoh.github.io/blog/reducing-cloud-bill;
    }

    location /ui {
        return 302 https://nicholasgoh.github.io/blog/reducing-cloud-bill;
    }

    location /_next/static {
        return 302 https://nicholasgoh.github.io/blog/reducing-cloud-bill;
    }

    location /_next/webpack-hmr {
        return 302 https://nicholasgoh.github.io/blog/reducing-cloud-bill;
    }

    location /api/ {
        return 302 https://nicholasgoh.github.io/blog/reducing-cloud-bill;
    }

    location /api/docs {
        return 302 https://nicholasgoh.github.io/blog/reducing-cloud-bill;
    }

    location /use-cases/customer-service/ui {
        return 302 https://nicholasgoh.github.io/blog/reducing-cloud-bill;
    }

    location /use-cases/customer-service/api/ {
        return 302 https://nicholasgoh.github.io/blog/reducing-cloud-bill;
    }

    location /use-cases/customer-service/api/docs {
        return 302 https://nicholasgoh.github.io/blog/reducing-cloud-bill;
    }

    location /use-cases/etl-automation/ui {
        return 302 https://nicholasgoh.github.io/blog/reducing-cloud-bill;
    }

    location /use-cases/etl-automation/api/ {
        return 302 https://nicholasgoh.github.io/blog/reducing-cloud-bill;
    }

    location /use-cases/etl-automation/api/docs {
        return 302 https://nicholasgoh.github.io/blog/reducing-cloud-bill;
    }
}
